const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync('index.html','utf8').replace(/\r\n/g,'\n'),helper=fs.readFileSync('js/staffRendering.js','utf8');
const patches=require('./map-ui-optimization-patch.json');
assert(!helper.includes('radarPulse'));assert(!html.slice(html.indexOf('async function loadSightings('),html.indexOf('async function syncElephantSightingsToIDBBatch(')).includes('radarPulse'));
assert(html.includes('.radarPulse {')&&html.includes('@keyframes radarPulseWave')&&html.includes('<div class="radarPulse riskPulseRed"></div>'),'Unrelated animations retained');
assert(/\.btr-team-monitoring::before/.test(fs.readFileSync('css/tigerTeams.css','utf8')), 'Only SBMT pulse selector is present');
const p=patches['index.html'].find(p=>p.after.includes('const previousPosition'));
let moves=0,icons=0;const icon={options:{html:'fresh',iconSize:[30,30],iconAnchor:[15,15],className:''}};
const marker={options:{icon:JSON.parse(JSON.stringify(icon))},getLatLng:()=>({lat:26,lng:89}),setLatLng(){moves++},setIcon(i){icons++;this.options.icon=i}};
vm.runInNewContext(p.after,{marker,icon,lat:26,lon:89});assert.equal(moves,0);assert.equal(icons,0);
vm.runInNewContext(p.after,{marker,icon,lat:26.1,lon:89});assert.equal(moves,1);assert.equal(icons,0);
const stale={options:{...icon.options,html:'stale'}};vm.runInNewContext(p.after,{marker,icon:stale,lat:26,lon:89});assert.equal(icons,1,'Status changes replace icon');
const positionPatch=patches['index.html'].find(p=>p.after.includes('final overlap-adjusted'));let fallbackMoves=0,refreshes=0;
const window={StaffPopup:{setPosition(){fallbackMoves++}},StaffRendering:{refresh(){refreshes++}}};
const move=vm.runInNewContext('(function(){'+positionPatch.after+'})',{window,marker,lat:26,lon:89});move();assert.equal(refreshes,1);assert.equal(fallbackMoves,0,'No raw-position intermediate update for overlap');delete window.StaffRendering;move();assert.equal(fallbackMoves,1,'Legacy fallback retained');
const start=html.indexOf('window.BTRMapInteractionDiagnostics ='),end=html.indexOf('})(map);',start)+9;let listeners=0,wheels=0,cameras=0;
const container={addEventListener(){wheels++},removeEventListener(){wheels--}};const map={getCenter:()=>({lat:26,lng:89}),getZoom:()=>14,getContainer:()=>container,on(){listeners++},off(){listeners--},setView(){cameras++;return this},setZoom(){cameras++;return this}};
const original=map.setView,c={map,window:{},performance:{now:()=>1}};vm.runInNewContext(html.slice(start,end),c);const diag=c.window.BTRMapInteractionDiagnostics;
assert.equal(listeners,0);assert.equal(wheels,0);assert.equal(map.setView,original);assert.equal(diag.report().length,0);
diag.start();diag.start();assert.equal(listeners,1);assert.equal(wheels,1);assert.strictEqual(map.setView(),map);assert.equal(cameras,1);assert(diag.report().some(r=>r.type==='camera:setView'));
for(let i=0;i<600;i++)map.setZoom();assert.equal(diag.report().length,500);diag.stop();assert.equal(map.setView,original);assert.equal(listeners,0);assert.equal(wheels,0);assert.equal(cameras,601);
console.log('PASS scoped radar removal, unchanged/changed elephant icon and position, staff position ownership, disabled trace overhead, idempotent start/stop, bounded trace and deliberate camera operations');
